FROM alpine:3.15
RUN apk --no-cache add \
    curl \
    nano \
    tcpdump && \ 
    rm -rf \
   /tmp/* 
#    adduser -s /bin/sh nees 

#RUN echo "root:nees" | chpasswd && \ 
#    echo "nees:pees" | chpasswd
